from django.urls import path
from .views import BookList, BookViewSet
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

#Set up router and register viewsets
router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename= 'book_all')

urlpatterns = [
    #ListAPIView endpoint for listing books
    path('books/', BookList.as_view(), name='book-list'),

    #CRUD routes generated by the router
    path('', include(router.urls)),
]