from django.urls import path
from .views import BookList, BookViewSet
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token

#Set up router and register viewsets
router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename= 'book_all')

urlpatterns = [
    #ListAPIView endpoint for listing books
    path('books/', BookList.as_view(), name='book-list'),
    #Endpoint for obtaining auth tokens - allows users to POST usernames and passwords to receive tokens
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),

    #CRUD routes generated by the router
    path('', include(router.urls)),
]